{
 "title": "Devops Assessment",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "assessmentMonth",
    "label": "Assessment Month",
    "query": "select distinct to_char(assessment_date, 'YYYY-MM-DD') from pod_devops_assessment pda order by to_char(assessment_date, 'YYYY-MM-DD') desc"
   },
   {
    "name": "productId",
    "label": "Product Id",
    "query": "7abc175c-4399-4ac3-9ce8-39612d84b98b"
   },
   {
    "name": "vsId",
    "label": "Value Stream Id",
    "query": "dd316e6a-ddde-4143-8681-e1319ba5f54d"
   },
   {
    "name": "podId",
    "label": "Pod Id",
    "query": "dd316e6a-ddde-4143-8681-e1319ba5f54d"
   }
  ]
 },
 "panels": [
  { "title": "Overall Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Average Maturity Level (All Capabalities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #ffffff;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand assessment_date = '$assessmentMonth'\n"
    }
   ]
  },
  {
   "title": "Technical",
   "type": "stat",
   "description": "Average Maturity Level (Technical Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Technical Capabilities'\nand assessment_date = '$assessmentMonth'\n"
    }
   ]
  },
  {
   "title": "Process",
   "type": "stat",
   "description": "Average Maturity Level (Process Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #ffffff;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Process Capabilities'\nand assessment_date = '$assessmentMonth'\n"
    }
   ]
  },
  {
   "title": "Measurement",
   "type": "stat",
   "description": "Average Maturity Level (Measurement Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #ffffff;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Measurement Capabilities'\nand assessment_date = '$assessmentMonth'\n"
    }
   ]
  },
  {
   "title": "Respondents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct response_id)\nfrom pod_devops_assessment pda\nwhere 1 = 1\n--and (pod_id::text in ($podId) or vs_id::text in($vsId) or product_id::text in($productId))\nand assessment_date = '$assessmentMonth'"
    }
   ]
  },
  { "title": "My Results (Filtered by Layer)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Average Maturity Level (All Capabalities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n"
    }
   ]
  },
  {
   "title": "Technical",
   "type": "stat",
   "description": "Average Maturity Level (Technical Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Technical Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n"
    }
   ]
  },
  {
   "title": "Process",
   "type": "stat",
   "description": "Average Maturity Level (Process Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Process Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n"
    }
   ]
  },
  {
   "title": "Measurement",
   "type": "stat",
   "description": "Average Maturity Level (Measurement Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n round(100.0*avg(answer_result)::decimal, 2) total\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Measurement Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))"
    }
   ]
  },
  {
   "title": "Respondents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct response_id)\nfrom pod_devops_assessment pda\nwhere 1 = 1\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\nand assessment_date = '$assessmentMonth'"
    }
   ]
  },
  {
   "title": "Technical",
   "type": "bargauge",
   "description": "Maturity Level by Capability (Technical Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Total\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Technical Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Total\""
    }
   ]
  },
  {
   "title": "Process",
   "type": "bargauge",
   "description": "Maturity Level by Capability (Process Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Total\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Process Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Total\""
    }
   ]
  },
  {
   "title": "Measurement",
   "type": "bargauge",
   "description": "Maturity Level by Capability (Measurement Capabilities)\n<table style=\"border-collapse: collapse; width: 100%; height: 54px;\" border=\"1\">\n<tbody>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #E90011;\"><strong><span style=\"color: #ffffff;\">Not Installed</span></strong></td>\n<td style=\"width: 25%; text-align: center; height: 18px; background-color: #FF9213;\"><strong><span style=\"color: #ffffff;\">WIP</span></strong></td>\n<td style=\"width: 25%; height: 18px; text-align: center; background-color: #003575;\"><strong><span style=\"color: #FFFFFF;\">Installed</span></strong></td>\n</tr>\n<tr style=\"height: 18px;\">\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-100% to -20%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>-20% to 60%</em></span></td>\n<td style=\"width: 25%; height: 18px; text-align: center;\"><span style=\"color: #808080;\"><em>60% to 100%</em></span></td>\n</tr>\n</tbody>\n</table>\n",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Total\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand category_name not in('Feedback')\nand capability_name not in('Feedback')\nand category_name = 'Measurement Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Total\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "Source: Last Capabilities Assessment.\nThis Capabilities Assessment was strongly inspired by <a href=\"https://www.devops-research.com/research.html\" target=\"_blank\">DORA Research</a>\n"
   }
  },
  {
   "title": "Compare with Previous Assessments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Technical",
     "type": "barchart",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Current\",\n (\n\tselect\n\t round(100.0*avg(pdac2.answer_result)::decimal, 2)\n\tfrom pod_devops_assessment_capabilities pdac2\n\twhere 1 = 1\n\tand category_name = 'Technical Capabilities'\n\tand pdac2.capability_name = pdac.capability_name\n\tand pdac2.assessment_date = (select max(assessment_date) from pod_devops_assessment pda where pda.assessment_date < '$assessmentMonth')\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n ) \"Previous\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand capability_name not in('Feedback')\nand category_name = 'Technical Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Current\""
      }
     ]
    },
    {
     "title": "Process",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Current\",\n (\n\tselect\n\t round(100.0*avg(pdac2.answer_result)::decimal, 2)\n\tfrom pod_devops_assessment_capabilities pdac2\n\twhere 1 = 1\n\tand category_name = 'Process Capabilities'\n\tand pdac2.capability_name = pdac.capability_name\n\tand pdac2.assessment_date = (select max(assessment_date) from pod_devops_assessment pda where pda.assessment_date < '$assessmentMonth')\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n ) \"Previous\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand capability_name not in('Feedback')\nand category_name = 'Process Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Current\""
      }
     ]
    },
    {
     "title": "Measurement",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n capability_name ,\n round(100.0*avg(answer_result)::decimal, 2) \"Current\",\n (\n\tselect\n\t round(100.0*avg(pdac2.answer_result)::decimal, 2)\n\tfrom pod_devops_assessment_capabilities pdac2\n\twhere 1 = 1\n\tand category_name = 'Measurement Capabilities'\n\tand pdac2.capability_name = pdac.capability_name\n\tand pdac2.assessment_date = (select max(assessment_date) from pod_devops_assessment pda where pda.assessment_date < '$assessmentMonth')\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n ) \"Previous\"\nfrom pod_devops_assessment_capabilities pdac\nwhere 1 = 1\nand capability_name not in('Feedback')\nand category_name = 'Measurement Capabilities'\nand assessment_date = '$assessmentMonth'\nand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\ngroup by capability_name\norder by \"Current\""
      }
     ]
    }
   ]
  },
  {
   "title": "Not Applicable Answers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Working at Company",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select\n case \n  when tw.time_working is null or tw.time_working = '' then 'Not Informed'\n  else tw.time_working\n end time_working,\n round(100.0 * count(pdac.response_id) / \n  (select\n    case \n     when count(pdac2.response_id) = 0 then null\n     else count(pdac2.response_id)\n    end\n   from pod_devops_assessment_capabilities pdac2\n   where 1 = 1\n   and assessment_date = '$assessmentMonth'\n   and answer_type = 'YS'\n   and answer in('NA', 'N/A')\n   and (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n  )::decimal, 2)\nfrom (\n select 'Less than 3 months' time_working\n union\n select 'Less than a year' time_working\n union\n select 'A year or more' time_working\n union\n select '' time_working\n) tw\nleft join pod_devops_assessment pda\n on tw.time_working = pda.time_working \nleft join pod_devops_assessment_capabilities pdac\n on pda.response_id = pdac.response_id \n and pdac.answer_type = 'YS'\n and pdac.answer = 'NA'\n and pdac.assessment_date = '$assessmentMonth'\n and (pdac.pod_id::text in ('$podId') or pdac.vs_id::text in('$vsId') or pdac.product_id::text in('$productId'))\ngroup by\n tw.time_working\norder by\n case\n  when tw.time_working = 'Less than 3 months' then 0\n  when tw.time_working = 'Less than a year' then 10\n  when tw.time_working = 'A year or more' then 20\n  else 99\n end\n"
      }
     ]
    },
    {
     "title": "Technical",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "with total_ys as (\n\tselect\n\t capability_name ,\n\t count(*) total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n  and assessment_date = '$assessmentMonth'\n  and category_name in('Technical Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n)\nselect\n capability_name ,\n round(100.0 * total_na / total_ys::decimal, 2) total\nfrom (\n\tselect\n\t capability_name ,\n\t count(*) total_na,\n\t (select total\n\t  from total_ys ys\n\t  where ys.capability_name = pdac.capability_name ) total_ys\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand category_name in('Technical Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand answer in('NA', 'N/A')\n\tand assessment_date = '$assessmentMonth'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n) total\norder by total desc\n"
      }
     ]
    },
    {
     "title": "Process",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "with total_ys as (\n\tselect\n\t capability_name ,\n\t count(*) total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n  and assessment_date = '$assessmentMonth'\n  and category_name in('Process Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n)\nselect\n capability_name ,\n round(100.0 * total_na / total_ys::decimal, 2) total\nfrom (\n\tselect\n\t capability_name ,\n\t count(*) total_na,\n\t (select total\n\t  from total_ys ys\n\t  where ys.capability_name = pdac.capability_name ) total_ys\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand category_name in('Process Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand answer in('NA', 'N/A')\n\tand assessment_date = '$assessmentMonth'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n) total\norder by total desc\n"
      }
     ]
    },
    {
     "title": "Measurement",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 9, "x": 15, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "with total_ys as (\n\tselect\n\t capability_name ,\n\t count(*) total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n  and assessment_date = '$assessmentMonth'\n  and category_name in('Measurement Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n)\nselect\n capability_name ,\n round(100.0 * total_na / total_ys::decimal, 2) total\nfrom (\n\tselect\n\t capability_name ,\n\t count(*) total_na,\n\t (select total\n\t  from total_ys ys\n\t  where ys.capability_name = pdac.capability_name ) total_ys\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand category_name in('Measurement Capabilities')\n\tand capability_name not in('Feedback')\n\tand answer_type = 'YS'\n\tand answer in('NA', 'N/A')\n\tand assessment_date = '$assessmentMonth'\n\tand (pod_id::text in ('$podId') or vs_id::text in('$vsId') or product_id::text in('$productId'))\n\tgroup by\n\t capability_name \n) total\norder by total desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Respondents Profile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Working at Company",
     "type": "barchart",
     "description": "Time Working at Company",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": " select\n case \n  when tw.time_working is null or tw.time_working = '' then 'Not Informed'\n  else tw.time_working\n end time_working,\n count(pda.response_id) \"Total\"\nfrom (\n select 'Less than 3 months' time_working\n union\n select 'Less than a year' time_working\n union\n select 'A year or more' time_working\n union\n select '' time_working\n) tw\nleft join pod_devops_assessment pda\n on tw.time_working = pda.time_working \n and (pda.pod_id::text in ('$podId') or pda.vs_id::text in('$vsId') or pda.product_id::text in('$productId'))\n and pda.assessment_date = '$assessmentMonth'\nwhere 1 = 1\ngroup by tw.time_working\norder by\n case\n  when tw.time_working = 'Less than 3 months' then 0\n  when tw.time_working = 'Less than a year' then 10\n  when tw.time_working = 'A year or more' then 20\n  else 99\n end\n"
      }
     ]
    },
    {
     "title": "Was it your first time answering this assessment",
     "type": "barchart",
     "description": "Was it your first time answering this assessment",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select ans.answer, coalesce(pdac.total, 0) \"Total\"\nfrom (\n\tselect distinct answer \n\tfrom pod_devops_assessment_capabilities pdac \n\twhere question = 'Was it your first time answering this assessment'\n\tand answer is not null and answer <> '' and answer <> '0'\n\tunion\n\tselect 'Not Informed' answer\n) ans\nleft join (\n\tselect\n\t case\n\t  when pdac.answer is null then 'Not Informed'\n\t  else pdac.answer\n\t end answer, \n\t count(*) Total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand (pdac.pod_id::text in ('$podId') or pdac.vs_id::text in('$vsId') or pdac.product_id::text in('$productId'))\n\tand pdac.assessment_date = '$assessmentMonth'\n\tand pdac.question = 'Was it your first time answering this assessment'\n\tgroup by pdac.answer\n) pdac\non ans.answer = pdac.answer \n"
      }
     ]
    },
    {
     "title": "I Have a Good Knowledge About DevOps",
     "type": "barchart",
     "description": "I Have a Good Knowledge About DevOps",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
     "targets": [
      {
       "rawSql": "select ans.answer, coalesce(pdac.total, 0) \"Total\"\nfrom (\n\tselect distinct answer \n\tfrom pod_devops_assessment_capabilities pdac \n\twhere question = 'I have a good knowledge about DevOps'\n\tand answer is not null and answer <> ''\n\tunion\n\tselect 'Not Informed' answer\n) ans\nleft join (\n\tselect\n\t case\n\t  when pdac.answer is null then 'Not Informed'\n\t  else pdac.answer\n\t end answer, \n\t count(*) Total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand (pdac.pod_id::text in ('$podId') or pdac.vs_id::text in('$vsId') or pdac.product_id::text in('$productId'))\n\tand pdac.assessment_date = '$assessmentMonth'\n\tand pdac.question = 'I have a good knowledge about DevOps'\n\tgroup by pdac.answer\n) pdac\non ans.answer = pdac.answer \norder by\n case\n  when ans.answer = 'Strongly disagree' then 10\n  when ans.answer = 'Disagree' then 20\n  when ans.answer = 'Neutral' then 30\n  when ans.answer = 'Agree' then 40\n  else 50\n end"
      }
     ]
    },
    {
     "title": "I Had No Difficulties Answering this Questionnaire",
     "type": "barchart",
     "description": "I Had No Difficulties Answering this Questionnaire",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "select ans.answer, coalesce(pdac.total, 0) \"Total\"\nfrom (\n\tselect distinct answer \n\tfrom pod_devops_assessment_capabilities pdac \n\twhere question = 'I had no difficulties answering this questionnaire'\n\tand answer is not null and answer <> '' and answer <> '0'\n\tunion\n\tselect 'Not Informed' answer\n) ans\nleft join (\n\tselect\n\t case\n\t  when pdac.answer is null then 'Not Informed'\n\t  else pdac.answer\n\t end answer, \n\t count(*) Total\n\tfrom pod_devops_assessment_capabilities pdac\n\twhere 1 = 1\n\tand (pdac.pod_id::text in ('$podId') or pdac.vs_id::text in('$vsId') or pdac.product_id::text in('$productId'))\n\tand pdac.assessment_date = '$assessmentMonth'\n\tand pdac.question = 'I had no difficulties answering this questionnaire'\n\tgroup by pdac.answer\n) pdac\non ans.answer = pdac.answer \norder by\n case\n  when ans.answer = 'Strongly disagree' then 10\n  when ans.answer = 'Disagree' then 20\n  when ans.answer = 'Neutral' then 30\n  when ans.answer = 'Agree' then 40\n  else 50\n end"
      }
     ]
    }
   ]
  }
 ]
}