{
 "title": "MTTR Details",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "prodId", "label": "Galaxy Product Id" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "blocker issues" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "This product had",
     "query": "SELECT count(issueName) FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Mean downtime",
     "query": "SELECT mean(mttr)/3600000 FROM mean_time_to_recover WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Worst downtime",
     "query": "SELECT max(crisisduration)/3600000 FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "# of incidents by month",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_correctionLevel",
     "query": "SELECT value FROM mttr_by_correction_level WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY correctionLevel"
    }
   ]
  },
  {
   "title": "More affected country",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"crisisDuration\"), country FROM (SELECT sum(crisisDuration) as \"crisisDuration\", last(country) as \"country\" FROM mttr_by_country WHERE productId =~ /^(${prodId:pipe})$/ and $timeFilter GROUP BY country)"
    }
   ]
  },
  {
   "title": "Main issue type",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"errorTypeCount\"), errorType FROM (SELECT count(errortype) as \"errorTypeCount\", last(\"errortype\") as \"errorType\" FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ GROUP BY errortype)"
    }
   ]
  },
  {
   "title": "More affected platform",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"crisisDuration\"), platform FROM (SELECT sum(crisisDuration) as \"crisisDuration\", last(platform) as \"platform\" FROM mttr_by_platform WHERE productId =~ /^(${prodId:pipe})$/ and $timeFilter GROUP BY platform)"
    }
   ]
  },
  { "title": "by Squad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "# of incidents by Squad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_targetSquad",
     "query": "SELECT value FROM mttr_by_target_squad WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY targetSquad"
    }
   ]
  },
  {
   "title": "# Total of incidents by Squad",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_targetSquad",
     "query": "SELECT sum(value) FROM mttr_by_target_squad WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY targetSquad"
    }
   ]
  },
  {
   "title": "by Platform",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downtime by Platform",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_platform",
       "query": "SELECT crisisDuration FROM mttr_by_platform WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY platform"
      }
     ]
    },
    {
     "title": "More affected platforms",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_platform",
       "query": "SELECT sum(crisisDuration) FROM mttr_by_platform WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY platform"
      }
     ]
    }
   ]
  },
  {
   "title": "by Country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downtime by Country",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_country",
       "query": "SELECT crisisDuration FROM mttr_by_country WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY country"
      }
     ]
    },
    {
     "title": "More affected countries",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_country",
       "query": "SELECT sum(crisisDuration) FROM mttr_by_country WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY country"
      }
     ]
    }
   ]
  },
  {
   "title": "by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of incidents by Type",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_errortype",
       "query": "SELECT count(errortype) FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY errortype"
      }
     ]
    },
    {
     "title": "# of incidents by Subtype",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_errorsubtype",
       "query": "SELECT count(errorsubtype) FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ AND $timeFilter GROUP BY errorsubtype"
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataset",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"crisisenddate\", \"issueName\", \"crisisduration\", \"crisisduration\" as \"c2\", \"summary\", \"affectedcountries\",\"affectedplataforms\",\"affectedproduct\",\"affectedsquads\", \"targetsquad\", \"components\",\"correctionlevel\",\"errortype\",\"errorsubtype\",\"issueType\",\"priority\",\"status\",\"statusCategory\" FROM jira_incidents WHERE productId =~ /^(${prodId:pipe})$/ and $timeFilter ORDER BY time DESC",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}