{
 "title": "Tech Metrics",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "4-key metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment frequency (per week)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Deployments per week",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") as deploys FROM \"deploy\" GROUP BY time(1w, 3d) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deployment failure rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deploy",
     "query": "select 100-(mean(\"success\")*100) from deploy where $timeFilter",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cycle time post dev",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AVG",
     "measurement": "build",
     "query": "SELECT mean(\"duration\") FROM \"deploy\" WHERE success = 1 AND $timeFilter",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "WORST",
     "query": "SELECT max(deployDuration) FROM (SELECT \"duration\" AS deployDuration FROM \"deploy\" WHERE success = 1 AND $timeFilter GROUP BY \"project\" )"
    }
   ]
  },
  {
   "title": "Build duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "AVG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration\") FROM \"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "WORST",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(projectDuration) FROM (SELECT \"duration\" AS projectDuration  FROM \"build\" WHERE $timeFilter GROUP BY \"project\" )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Deploy data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "# of succeeded deploys by project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select count(success) from deploy where $timeFilter and success = 1 group by project"
    }
   ]
  },
  {
   "title": "# of deploy interval by project",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select \"duration\" from deploy where $timeFilter and success = 1 group by project"
    }
   ]
  },
  {
   "title": "# of failed deploys by project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select count(success) from deploy where $timeFilter and success = 0 group by project"
    }
   ]
  },
  { "title": "Build data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "# of succeeded builds by project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select count(success) from build where $timeFilter and success = 1 group by project"
    }
   ]
  },
  {
   "title": "# of build duration by project",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select \"duration\" from build where $timeFilter  group by project"
    }
   ]
  },
  {
   "title": "# of failed builds by project",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_project",
     "query": "select count(success) from build where $timeFilter and success = 0 group by project"
    }
   ]
  }
 ]
}